version: 2

jobs:
  build:
    working_directory: ~/laravel
    docker:
      - image: notnoopci/php:7.2-apache-node
      environment:
        MYSQL_HOST: 127.0.0.1
        MYSQL_DB: laravel_passport
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: false
        MYSQL_PASSWORD: root
          - image: mysql:5.7
            command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
            environment:
              MYSQL_USER: root
              MYSQL_ALLOW_EMPTY_PASSWORD: false

    steps:
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: Install Composer
          command: 'curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer'
      - run:
          name: Display versions
          command: |
            php -v
            composer --version
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer update
#      - run:
#          name: Install project dependencies
#          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          name: Run PhpUnit
          command: ./vendor/bin/phpunit
